### ISSUE TITLE
Attempted to remove more RCTKeyboardObserver listeners than added

### ISSUE THREAD

**Issue by Yann-prak** [rlemasquerier/react-native-keyboard-scrollview#1] opened 2023-10-25 13:40 UTC
Hey,

First of all, thank you, this is simple and easy to use, exactly what I was looking for ! 

I tried your library in my project and I have this error `Attempted to remove more RCTKeyboardObserver listeners than added`.

To reproduce in simulator: 
- Install react-navigation
- Navigate to a page
- Open the keyboard
- Go back without dismissing the keyboard

I've found that if you dismiss the keyboard (cmd+k) then go back, the error is thrown anyway.

I can't find where it could come from. Do you have any idea ?

**Comment by joshkitt** [comment] 2023-11-01 20:23
I see the same thing. Looking at the code, I think the Keyboard.removeAllListeners on lines 83-85 of KeyboardScrollView.tsx could be changed to remove only the listeners which were added earlier in the useEffect hook (would probably need to refactor the listeners into functions with a variable so it can be referenced later in the remove). That might fix it.

@rlemasquerier Thanks for your work on this. I'm hoping to use it to replace the other library that isn't maintained.

**Comment by rlemasquerier** [comment] 2023-11-03 11:43
Hello @Yann-prak @joshkitt 

Thanks a lot for letting me know the issue.

I have added react-navigation to the example app to try to reproduce the issue, but I didn't trigger the error. Maybe it depends on the version of react-navigation used?

Even if I didn't reproduce the error,  I replaced the usage of `removeAllListeners` by removing only the created listeners as you suggested @joshkitt , because I find it way cleaner, but I can't confirm it will fix your issue.

In addition, I noticed some broken behaviour when moving between stack screens with the keyboard NOT closed - I'll have a deeper look 👀

**Comment by Yann-prak** [comment] 2023-11-03 14:46
Hey !

I've tested the fixed and it worked. No more error thrown :)

I think we can close this issue, thanks a lot @joshkitt & @rlemasquerier !

**Comment by rlemasquerier** [comment] 2023-11-03 15:15
Great news, I close the issue then, thanks for confirming @Yann-prak

**Closed as completed by rlemasquerier** 2023-11-03 15:15 UTC

**Comment by joshkitt** [comment] 2023-11-03 15:44
Thanks! I was starting to work on a PR, but you beat me to it. Glad it's working.
